### ISSUE TITLE
Expose screenshot captions

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1027]
Screenshots can optionally have a translatable caption. We should expose this somewhere, perhaps below the screenshot or as a tooltip.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

Suggested at https://twitter.com/phase1g_o/status/1146395526319005697

**Comment by Antolius** [comment]
Hi! Would you mind me taking a crack at this issue?

It seems relatively simple to implement, with perhaps the biggest question being what we want it to look like in the end (hence the "Needs Design" label). I implemented a prototype of the "caption as a tooltip" approach, because I feare space below images might get a bit crowded with both the caption and the carousel indicator dots.

Here are two examples of this approach.

In case of "sparse" screenshot (i.e. without too much visual elements) it looks OK to me:
![sparse-screenshot](https://user-images.githubusercontent.com/5374391/147991434-39c780bf-d9b5-4846-bac7-5eac024fc074.png)

In case of a bussy screenshot the tooltip might be getting a bit lost:
![bussy-screenshot](https://user-images.githubusercontent.com/5374391/147991438-144d4103-b718-4769-b559-2f5eb8bee43f.png)

@cassidyjames what do you think? Would you like me to put together a prototype for the "label below the screenshot" approach, or does tooltip look good enough? If you'd like to play around with it yourself you can check out the linked draft PR.

**Comment by cassidyjames** [comment]
@Antolius I am a fan of the tooltip, at least to start! I think exposing it beneath the screenshot _might_ work, but I also don't want to crowd the rest of the app page out since there's already a lot going on at the top. If we get it in as a tooltip, it'll be easier to rework the design in the future if we want, too.
