### ISSUE TITLE
AppCenter not showing new version number for the app updates

### ISSUE THREAD

**Issue by uncertainquark** [elementary/appcenter#1042]
I've noticed on several occasions that AppCenter shows the current installed version number of the app on the "Updates" screen rather than the one it's updating to. Firefox is the most prominent example for this. Here's an old screenshot where the Firefox version number is actually 67 but the updater shows the installed version 66.0.5.

![Screenshot from 2019-05-22 08-48-03](https://user-images.githubusercontent.com/22585732/61924517-c872f900-af85-11e9-9832-62428ecc0bba.png)

**Comment by NathanBnm** [comment]
I've the same issue. This happens with some elementary apps too. And when the wrong version number is displayed, the changelog corresponds to this version and not to the new version of the app.

**Comment by 4jNsY6fCVqZv** [comment]
I wonder if it is intended to display the old version instead of the new one?

Personally, I am always irritated to see the old version when I read for example in articles that the new Firefox version is out now. And AppCenter shows me an update for the old version. But of course, it's an update for the old version. No update to the old version. A matter of perception probably.

**Comment by Vortex-TH** [comment]
Can we have AppCenter show both the version that is installed and the one that is upgraded to?

**Comment by danirabbit** [comment]
I'm going to close this since we now group all PackageKit updates as part of offline updates. The issue here was that AppStream data was always out of date because it actually had to be downloaded and updated itself.
