### ISSUE TITLE
Restart required infobar no longer shows

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1048]
Can't seem to get it to show with `sudo touch /var/run/reboot-required`, and it doesn't show after kernel updates anymore.

**Comment by vjr** [comment]
@davidmhewitt the `private void updates_changed_callback ()` never seems to get signalled based on my rudimentary tests (`pkcon refresh` or `sudo apt update`)...

**Comment by vjr** [comment]
@davidmhewitt could it be due to running the packagekit code in a worker thread that the signal for the callback is not getting propagated?

i am not familiar with the glib/gtk threading rules but some googling around seems to indicate to me there could be a problem with either sending signals across threads or the `g_timeout_add` that is there in the packagekit source where the `updates_changed` signal is emitted.

i did try removing the timeout in packagekit source with no luck and trying to move the signal across threads or just removing the use of a thread in appcenter is daunting for me at the moment.
