### ISSUE TITLE
Add changelog or fix for the current deployed version

### ISSUE THREAD

**Issue by Nikoos** [elementary/appcenter#1099]
Hi,

Could it be possible to add the current changelog (or fix) provided in the installed version. For instance, when I looked at the Camera application page in AppCenter, could we have a link to a list of fixed issue for the deployed version (or maybe a link to a github release page) ?

Thanks for your hard work.

Nikos

_Originally posted by @Nikoos in https://github.com/elementary/appcenter/issues/944#issuecomment-536176060_

**Comment by cassidyjames** [comment]
We do have AppStream changelogs right now, though I think the logic is to show the most recent version. The problem with first-party apps like Camera right now is that the AppStream data is generated separately, and I think it's out of date. The goal is to distribute first-party apps through AppCenter just like third-party apps which will help ensure AppStream data is up to date as well.

**Comment by 4jNsY6fCVqZv** [comment]
Complementary observation:

While Camera and Calculator simply display the latest version without a changelog, AppCentre 3.2.0 displays "What's New: 0.2.9 ..." and Calendar "What's New: 0.4.2.1 ..." or Files "What's New: 0.35 ...".

I didn't check all the apps. But I would want a consistent procedure for all native default apps. Preferably with current changelogs, so that not so technical users better understand what has changed and how through an update.

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv because first-party packages are distributed via our PPA (since it includes a lot more CD/CI than the current Houston process, plus a lot more than just "apps"). As I stated, the goal is to get them into Houston but for now they will still be distributed through the PPA.

Unfortunately, PPAs do not generate/support AppStream data. Consequently, we have to generate it separately. We're working to automate this process, but the previous person in change of this had never updated it. The process is in this repo: https://github.com/elementary/appstream-data
