### ISSUE TITLE
Most Flatpak apps don't show in categories

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#1114]
I don't think this is just an upstream metadata issue, as it happens to so many apps which should have the correct metadata. I'll try and gather some concrete examples with links to metadata to confirm.

I noticed this a while back but forgot about it, but someone else has since brought it up on Twitter since the 3.2 release.

**Comment by Akzel94** [comment]
From my own testing:

There are apps that don't show up in categories at all, such as Discord and FeedReader.

Some apps, like GNOME Boxes, do show up when browsing categories, as the Ubuntu package and Flatpak version are under the same app listing, via the drop-down menu.

Other Flatpak apps, like Telegram, that aren't under the same listing as the equivalent Ubuntu package also fail to show in categories.

**Comment by zelikos** [comment]
More testing will be needed, but it may be safe to say this isn't a metadata issue. When browsing AppCenter immediately after launching it, I did see Flatpak apps in categories at first. When the results finished loading, though, it seemed that the Flatpak results may have been replaced with the non-Flatpak results, rather than showing up alongside them.
