### ISSUE TITLE
Scrolling through app listing causes abrupt shifting of the viewport

### ISSUE THREAD

**Issue by JessiAuro** [elementary/appcenter#1212]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Scrolling through the listings of any of the app categories causes the listing to shift back upwards as new results are loaded in.

### To Reproduce
1. Open AppCenter
2. Select a category
3. Scroll down until it has to load additional listings

Note: I was using the mouse wheel on my external mouse.

### Expected behavior
Smooth, uninterrupted scrolling through the app listing. 

### Screenshots or screen recordings
[Screen recording of the bug](https://youtu.be/tsU8B6Mytak)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by davidmhewitt** [comment]
As a result of testing this out for myself, I realised results were loading in a strange order which has since been fixed and released in https://github.com/elementary/appcenter/pull/1213

So this is improved a bit now, but loading results in real time is always a bit jumpy with GTK listboxes. We'll have to look if there are ways to improve this further.
