### ISSUE TITLE
Wrong display with HighContrast

### ISSUE THREAD

**Issue by Angedestenebres** [elementary/appcenter#1220]
As said in the title, if you activate the HighContrast theme in accessibilities settings, the display of AppCenter is bad and some categories are even unreadable:

![Capture d'écran du 2020-02-22 14 16 48](https://user-images.githubusercontent.com/21110485/75093146-8b083580-557f-11ea-9ed0-6aebc1429393.png)

It also happens with some other themes but as the HighContrast is included by default it should offer a correct display with all applications :)

**Comment by danrabbit** [comment]
I'm going to close this as "Design conflict" since the high contrast theme is no longer recommended in a11y settings. The default stylesheet is intended to be contrast checked against WCAG AA. If there are issues with contrast, that should be considered an issue there. We should be accessible out of the box without requiring a separate stylesheet
