### ISSUE TITLE
Chrome shows up as system updates

### ISSUE THREAD

**Issue by bksubhuti** [elementary/appcenter#1227]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.
I don't know how to search..

## Describe the bug
Google chrome shows up as a system update rather than a single separate update like firefox.

If applicable, add screenshots or screen recordings to help explain your problem.
I already updated all (sorry)

### To Reproduce
sorry.. should have had a screen shot for you.

### Expected behavior

Should show up as a single separate app to update like firefox does

## Platform Information

 I'm using the latest released stable version

**Comment by lewisgoddard** [comment]
This is because of how Google Chrome is installed, typically as a debian file that adds its own repository as part of the installation process. I'm not sure there's any identifying feature to tell appcenter this is an independent app.

**Comment by bksubhuti** [comment]
It is so common for google chrome to be added.. perhaps  make a list of deb repos to check against it .. hand build the flat file but at least it is editable by you guys and not "hard coded"

**Comment by bksubhuti** [comment]
I wish they made an app image.  I dont like how browsers update every week.  we pay for data by the mb in myanmar

**Comment by 4jNsY6fCVqZv** [comment]
![Screenshot](https://user-images.githubusercontent.com/46536067/76616993-2fe1b700-651d-11ea-926f-870efdcb5ee6.png)

Made a similar observation. Installed the GNU communication solution Jami via direct web page developer repo through the terminal.
For example, I don't see the app in the "Installed" tab in AppCenter, nor when I search directly for the app name in AppCenter using the App Search. It's as if it's not there, although everything is running fine otherwise. It is also displayed in the application menu.

**Comment by davidmhewitt** [comment]
Applications display in AppCenter if they provide Appstream metainfo files. Since we are not in control of 3rd party applications or whether they provide appdata XMLs, I'm going to close this issue.

It sounds like this may be slightly related to #1015 however. I agree that these applications shouldn't really be categorized as "OS Updates".

**Comment by 4jNsY6fCVqZv** [comment]
The app already offers an appstream metainfo file.
take a look at https://git.jami.net/savoirfairelinux/ring-client-gnome/blob/master/jami-gnome.appdata.xml
