### ISSUE TITLE
User defined intervals for fetching updates

### ISSUE THREAD

**Issue by janga1** [elementary/appcenter#1237]
### Idea
I would like to be able to set the time intervals for fetching updates.

### Implementation
I think an implementation of this feature would be that a user would get some predefined options, like for example `once an hour`, `once a day`, `once a week`, `once month`.

The other option would be to let the user define exactly what he/she wants, e.g. `once every 235 hours`, but I don't think this would fit the ElementaryOS experience.

**Comment by danrabbit** [comment]
A concern I have with this is that we probably don’t want to let people unknowingly miss security updates

**Comment by janga1** [comment]
> A concern I have with this is that we probably don’t want to let people unknowingly miss security updates

I agree that this could be a potential problem.

**Comment by cassidyjames** [comment]
@janga1 can you share more about what problem you're trying to solve? Why should a user care at all exactly how often updates are checked for? I believe we currently check once a day and whenever the app is opened (assuming that the user is going to look for new apps or updates, so we should check then). It's unclear how that's not sufficient.

**Comment by janga1** [comment]
@cassidyjames, the idea came about because I want to update far less than once a day. The red bubble notifier in the Dock, however, is giving me anxiety. Maybe my request should have been about that.

Come to think of it, I would like to point out that it's odd that users can't turn off the red bubble indicators within the notification settings, since the icon for the notifications settings is a red bubble indicator:

![notifications_icon](https://user-images.githubusercontent.com/35235201/77816852-ab6b6880-70c6-11ea-9e57-cff59b429c0e.png)

I'll close the request, because I agree with @danrabbit that this feature request brings potential risks for users along with it.

**Comment by cassidyjames** [comment]
@janga1 I've filed issues for the dock badges:

- https://github.com/elementary/switchboard-plug-notifications/issues/64
- https://github.com/elementary/dock/issues/35

**Comment by janga1** [comment]
Thanks @cassidyjames, that would be awsome.

**Comment by cassidyjames** [comment]
Following up here since there are a few more reports from people asking for the same thing. It seems like the main reason people want to be able to manually set an update interval is because they're annoyed about being asked to update when we release a bunch of updates. 

I think the biggest way to resolve this is actually to move towards automatic updates. The other available methods of disabling notifications could also work, but I think for most updates, automatic would be the best experience. However, I'm not sure if there's a reliable and safe way to do so for apt updates; Ubuntu seems to have a way to automatically install some updates in the background iirc—perhaps we look into that? 

But ultimately, automatic Flatpak updates for apps and automatic image-based OS updates will be the ideal—if a bit far out—future.

**Comment by janga1** [comment]
Thanks for the follow up, @cassidyjames.

I definitely see the value in having this feature for other users, but I would most likely refrain from using automatic updates. Personally, I've had bad experiences with this functionality on both Win10, macOS, and Ubuntu. Instead I still would rather have the ability to switch off AppCenter's badges, just like you proposed earlier: https://github.com/elementary/appcenter/issues/1237#issuecomment-612207581.

**Comment by Oymate** [comment]
If there was a manual auto update flatpak option I would be happy
