### ISSUE TITLE
Uninstall and Open buttons aren't the same size

### ISSUE THREAD

**Issue by danirabbit** [elementary/appcenter#1322]
![Screenshot from 2020-05-14 09 20 02@2x](https://user-images.githubusercontent.com/7277719/81959361-2da2e400-95c4-11ea-9de3-db8692b7f204.png)

This is because SizeGroup includes margin in the widget's allocation. A way we could workaround this is to pack an extra empty grid instead of a 16px margin. I haven't tried if setting margin from CSS would fix this. Open to other solutions

**Comment by roshansingh** [comment]
Hey @danrabbit , should I try to make the open button compact by getting rid of the extra padding on left and right? Also I was wondering if the open should use a different color as it looks "disabled" to me.

**Comment by danrabbit** [comment]
The two buttons are intended to be homogenous in size. So the solution would not be to make the open button much smaller.

Styling is a different issue altogether and should be considered separately

**Comment by mcclurgm** [comment]
Is there something here that's stopping us from using `Gtk.Grid.column_spacing` instead of the margin? That's the first solution that comes to mind for me, since it seems like the only reason the margin exists is to space out the buttons.

**Comment by danrabbit** [comment]
@mcclurgm I'm not looking at the code right now but my guess is that one of these buttons is inside a revealer and we're not using column spacing so that we don't include double the spacing that's intended. But that's a good question! If we're not using a revealer here then that's probably the best solution

**Comment by mcclurgm** [comment]
Aha - that'll be it. All 3 buttons in the grid (uninstall, open, and "action button" that seems to be payment?) are in revealers. I think this is because we replace the open button with the action button when the user hasn't paid for the app. So in the layout you're showing here, there's a double space between the buttons. 

Maybe the solution is to add a new column like you said? That would add some more space in the middle of nowhere if the uninstall button is hidden, but probably better than everything else.

FWIW, here are the other crazy thoughts I had. I don't think either of them is really a good idea though:
If there's a way to tell SizeGroup to just subtract 12 from the uninstall button's allocation, that would be great. There are some functions to mess with allocation, but they're only used for 
We could also replicate the extra column by embedding the button in a grid with an empty 12px wide cell next to it. That way when we hide it, the spacer would go away too. But that may be going too far down the rabbit hole of nesting widgets?

**Comment by danirabbit** [comment]
The uninstall button is a little trash can now so, fixed :shrug: lol
