### ISSUE TITLE
Un-curated Ubuntu repositories should be replaced with Flathub

### ISSUE THREAD

**Issue by hanaral** [elementary/appcenter#1332]
I cannot recall the last time I found any useful un-curated apps apart from firefox. I think that the pretty bad selection of apps that is the un-curated section, should be replaced with Flathub entirely. 

The reason I'm asking this is just by asking around new users of elementary. It's quite obvious that many of these new users do not find the apps they are looking for within the AppCenter app, so they use external sources such as snaps, appimages and .debs (or even the flathub website), which deters them from using the AppCenter for anything other than updates.

I am by no means saying that Flathub should be given the same priority as curated apps, but just as a way to keep new users using the app as long as what they want is available in some way in the AppCenter GUI.

I haven't found any duplicates, but if I've managed to miss one somehow by all means close this issue (or transfer it)

**Comment by cassidyjames** [comment]
We've been discussing this a bit off and on. Right now, I think we're definitely looking at removing the Ubuntu repo apps (as it appears Ubuntu has done in their software center as of 20.04) since the results are so often low quality and sometimes nonfunctional on elementary OS. 

However, since it's so easy to add Flathub by installing a Flatpak from the site and then get Flathub apps in AppCenter, it doesn't seem super necessary to add it out of the box. Then again, if the majority of users (total speculation, we don't have the data) are adding Flathub anyway, it's possible that we could provide a better experience and better set expectations if we included it out of the box.

So this is really two issues:
1. Remove Non-curated Ubuntu repo apps, and
2. Include Flathub out of the box

I think we generally agree with 1, but 2 still needs some careful thought/discussion from the team.

**Comment by danrabbit** [comment]
I think there’s still kind of a concern with Flathub where there’s no real verification process for submissions and past actions indicates there’s no real requirement to adhere to ToS or redistribution agreements for proprietary apps. At least with the Ubuntu repos we know that they’re somewhat vetted and Canonical has some kind of legal obligation. I feel like we could potentially put ourselves at some level of legal risk by including FlatHub ootb

**Comment by hanaral** [comment]
That kinda sucks, I really hope there *is* a way to implement it somehow. The issue that I see is that poeple that are new, and likely have no idea what flathub is, don't tend to use the appcenter even after using flathub. Would it be possible to make it obvious that you can use flathub through the appcenter, without needing to directly say it? 

And on a somewhat related note, is it possible to give non-curated apps more visibility, like having a 'popular' section for flathub apps, below the curated ones?

**Comment by davidmhewitt** [comment]
AppCenter manages software for whatever software repositories are present/enabled on the system, it has no responsibility for choosing what those repositories are.

Even if there was a decision that Flathub would be included out of the box, no action would/could be taken in the AppCenter repository, so I'm going to close this issue.
