### ISSUE TITLE
Issues with my app center

### ISSUE THREAD

**Issue by chamanlavy** [elementary/appcenter#1392]
Hi! first of all, I want to congratulate yo as a team for you very good job with this SO. I really love it! I was a distrohooper who was changing from a distro to another every six months.

But, by otherwise, I have some issues with the app center. Previously, I tried to install R and Rstudio, and I made it! .. but the versions that I have are too old (3.4, and now they are in 4.0.2). I followed some advices about how to update it by terminal but the solution was worse, because now the app center couldn't update their files (I can update anther programs, but not the app center).

I hope this info helps, and thank you for your supprt.

**Comment by hanaral** [comment]
Hey
The AppCenter won't be able to identify apps istalled via other means. The reason why the non-elementary app on the AppCenter are so old is because elementary uses Ubuntu Long Term Support as a base. I'd hightly recommend checking out flathub.org for the apps you want, as it is essentially a cross-linux appstore that integrates in to the AppCenter search when you install something from there.

**Comment by danirabbit** [comment]
Closing since we no longer support Ubuntu repository apps and only support Flatpak remotes
