### ISSUE TITLE
Installing nvidia-driver-460 not working in daily build 31/04/21

### ISSUE THREAD

**Issue by joshuajaharwood** [elementary/appcenter#1509]
## What Happened
I tried installing nvidia-driver-460 from appcenter on a fresh daily build install. It reported the install succeeded, but after a reboot, nouveau is still being used. nvidia-settings can start, but only displays an empty box.

## Expected Behavior
After a reboot, the Nvidia proprietary drivers should be used, rather than nouveau.

## Steps to Reproduce

1. Install the 31/04 daily build for 6.0
2. Open appcenter
3. Click install on nvidia-driver-460
4. Reboot
5. Nvidia drivers still aren't listed under lsmod

## Platform Information
* elementary OS 6.0 Next, daily build for 31/03/21, amd64
* nvidia-driver-460 from the default repos
* Ryzen 7 1700
* 16GB DDR4
* 2 x Nvidia GeForce GTX 3070
* Displays
  * 1080p 60Hz vertically-aligned display 
  * 1440p 95Hz freesync horizontally-aligned display

**Comment by jonseppanen** [comment]
I had this issue to, and I found it was related to a grub-update misconfiguration.
Apparently it was mentioned on reddit that a fix is on the list for this, but can't seem to find it.
@cassidyjames is there an issue in the 6.0 release for this somewhere? because right now users cannot install nvidia drivers at all in the daily (nor can they update the kernel, fyi)

**Comment by cassidyjames** [comment]
This issue is being tracked here: https://github.com/elementary/os-patches/issues/168
