### ISSUE TITLE
Show relevant size of flatpak app rather than guessing the maximum

### ISSUE THREAD

**Issue by hanaral** [elementary/appcenter#1524]
## Problem

No matter what the cause, or how valid it is, people don't like being told that an app that is seemingly tiny could maybe take up to [X] hundreds of MBs. New users shouldn't face this dilemma even when updating, let alone installing a new app - I've had many instances where a sub 100MB update says it may take up to 1.3 GBs. 

## Proposal

Some ideas:
- Make appcenter calc the difference itself based on which libraries are already installed
- Calc the difference based on what *will* be preinstalled on a fresh install (i.e the io.elementary.Platform)
- List the size of the app when the necessary dependency is met, just show the size of the app when the dep is preinstalled

## Prior Art

Look at the macOS AppStore

**Comment by davidmhewitt** [comment]
This is a technical issue in that the Flatpak API does not provide an API to more accurately estimate the download size up front. There's an open issue here: https://github.com/flatpak/flatpak/issues/2627

Flatpak uses diff-based downloads where only the changed content of an app/runtime is downloaded. So if a runtime has an update, it could be 3KB because someone updated a translation, or it could be 1.3GB because all of the binary files within the runtime were replaced in a way that the diff-based updates couldn't handle. But we don't get that information until we're already part/most of the way through downloading it.

**Comment by hanaral** [comment]
Then maybe for now the download size (for flatpaks) should only be shown based on a precalculated difference between the updated app and the previous version in the appcenter backend. Is it really impossible to create a temporary workaround by handling the calculation on the elementary end?

**Comment by cassidyjames** [comment]
@davidmhewitt is this still the case? It looks like GNOME Software in GNOME 41 is doing something smarter.

![Screenshot from 2021-09-07 10 56 42](https://user-images.githubusercontent.com/611168/132383167-6f30397e-71e7-4ac8-a3ad-f5581045d21b.png)

**Comment by davidmhewitt** [comment]
It's probably still the case. It looks like they're displaying the size of the application and it's runtimes separately, which I guess is possible.

But it gets complex:

If you're installing an application and a bunch of runtimes you don't have installed already, then you can be pretty sure the size is just the sum of everything because you need to download 100% of all of them (there is no diff).

If you're installing a new application that depends on existing runtimes that don't need updating, then you can be sure of the size for the same reason as above.

If you're installing a new application that depends on runtimes that have updates available, then I _think_ Flatpak automatically updates them during the install of the app. You don't know how big this is gonna be up front due to the reasons outlined in my previous comment.

The same goes for outright updating apps/runtimes.

I'd need to look at the GNOME Software code to see how clever they were being with working out the above and showing "accurate" information or not.

**Comment by danrabbit** [comment]
I'm going to close this since the proper solution should probably be implemented in Flatpak instead of working around it in the client by trying to be clever
