### ISSUE TITLE
Wifi card driver in AppCenter doesn't work

### ISSUE THREAD

**Issue by mpanhans** [elementary/appcenter#1528]
## What Happened
After finishing installation of eOS 6, there is no way to connect to wifi because the wifi card is not recognized. After connecting via ethernet, a driver appears in the AppCenter called bcmwl-kernel-source. However, after installing this driver and rebooting, wifi is still not available.

I was eventually able to install the correct driver by following the instructions on the elementary StackExchange [here](https://elementaryos.stackexchange.com/questions/11783/elementary-os-on-macbook-wont-display-wifi-settings-how-do-i-fix). This involved running the following lines in terminal:

```
sudo apt-get remove --purge bcmwl-kernel-source
sudo reboot

sudo apt-get install firmware-b43-installer

sudo modprobe -r b43
sudo modprobe b43
```

## Expected Behavior
Ideally the wifi card would be available out-of-the-box after installing eOS 6. But at least it would be helpful if the correct driver was shown in the AppCenter.

## Steps to Reproduce
Install eOS on a MacBook Pro with a BCM4322 Broadcom network card.

## Platform Information

* eOS 6 Public Beta
* 2010 MacBook Pro with network controller BCM4322 802.11a/b/g/n

**Comment by davidmhewitt** [comment]
Thanks for the report, we're working on adding an option to the installer to install drivers. Details here: https://github.com/elementary/installer/issues/418

However, the logic for detecting which drivers to suggest in AppCenter (and the upcoming installer feature) is based on a program called `ubuntu-drivers`

So in your case, AppCenter has suggested `bcmwl-kernel-source` because that's what `ubuntu-drivers` has said is right for your hardware. So the issue lies with `ubuntu-drivers` (or possibly something even further upstream of it) and not with AppCenter. It looks like someone has already reported this issue against `ubuntu-drivers`: https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1860002

I'll close this issue as there's nothing we can do on the AppCenter side of things. Thanks again!
