### ISSUE TITLE
Get custom values from appstream components

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1555]
## What Happened

It doesn't appear that any custom values for an appstream component return non-null

## Expected Behavior

We should be able to get custom values like brand colors and stripe keys for flatpak apps

## Steps to Reproduce

1. Go to an app page for an app that has been published in AppCenter like Harvey
2. Notice that brand colors are not being used

You can also verify that this data is available in the local XML stored at ~`/.cache/io.elementary.appcenter/flatpak-metadata/user`

**Comment by davidmhewitt** [comment]
The metadata that ends up in `~/.cache/io.elementary.appcenter/flatpak-metadata/user` has the custom key/value attributes inside a `<metadata>` tag, whereas the source AppData xml has them inside a `<custom>` tag (which is where they're supposed to be).

I didn't look at it long enough to figure out what's doing that substitution somewhere between submission and release, but that's _why_ it's not working.

**Comment by davidmhewitt** [comment]
I suspect this is the culprit:

https://github.com/hughsie/appstream-glib/blob/6d6b8f488e4cd072818af037978e44fe61bf3415/libappstream-glib/as-app.c#L4832-L4839

Though I've been out of the game for a while so I'm not sure if/when that fits into the whole process of building a flatpak and pushing it to a remote.

**Comment by tintou** [comment]
In this line, there is no way that `as_node_context_get_version (ctx) > 0.9` might be true currently as the current version is 0.9 (from https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#spec-asxml-general )

**Comment by davidmhewitt** [comment]
I don't know, this might be one of those weird edge cases where libappstream-glib does things differently and has different tags compared to the pure appstream spec. There are references to version 1.0 in the libappstream-glib code:
 
https://github.com/hughsie/appstream-glib/blob/6d6b8f488e4cd072818af037978e44fe61bf3415/libappstream-glib/as-app.c#L6466

The AppStream spec also says this about the `<custom>` tag:

> The `<custom/>` tag is an optional tag which can be used as a key-value store for custom values that are not covered by the AppStream specification. The tag is usually stripped out or filtered by collection metadata generators, such as appstream-generator.

So I guess it is some version of libappstream-glib's generator that's doing the collection bundling, or else we wouldn't have those tags at all in our collection metadata.

**Comment by tintou** [comment]
The issue here is that the "collection" spec is a subset of the "metadata" set, so we are missing some fields as libappstream-glib is probably more pedantic regarding the specification than libappstream https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#spec-asxml-general
I've opened an issue upstream https://github.com/ximion/appstream/issues/339

**Comment by davidmhewitt** [comment]
The fields aren't missing in our collection files, they're inside a `<metadata>` tag on the component instead of a `<custom>` tag. I agree that according to the spec they shouldn't be there at all though.

There is a workaround we could do in AppCenter. We already do some amount of XML modification to be able to differentiate AppStream data from different remotes.

So, as well as that, we could remap the `<metadata>` (which doesn't seem to be a valid appstream tag at all) tag to `<custom>` and everything would just work while the appstream collection generator(s) are being fixed. I've just tested changing one of the components in the metadata collection cache manually and it just works :tm:

**Comment by davidmhewitt** [comment]
Here's a sample component from our collection file:

```
  <component type="desktop">
    <id>com.github.cassidyjames.dippi</id>
    <translation type="gettext">com.github.cassidyjames.dippi</translation>
    <name>Dippi</name>

...

    <metadata>
      <value key="x-appcenter-color-primary">#fff</value>
      <value key="x-appcenter-color-primary-text">#333</value>
      <value key="x-appcenter-suggested-price">3</value>
    </metadata>
    <bundle type="flatpak" runtime="io.elementary.Platform/x86_64/daily" sdk="io.elementary.Sdk/x86_64/daily">app/com.github.danrabbit.harvey/x86_64/master</bundle>
  </component>
```

The metadata that was in the `<custom>` tag in the original AppData XML file from Cassidy's repo has been mapped into the `<metadata>` tag, which as far as I can tell doesn't even exist?
