### ISSUE TITLE
`is_native` sometimes returning false negative

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#1564]
## What Happened

It seems like Package.is_native sometimes returns false for apps that are also available from non-curated sources

## Expected Behavior

If an app is available from AppCenter, `is_native` should return `true` even if it's available from a non-curated source too

## Steps to Reproduce

Adding a check for `is_native` to the banner on the homepage in [this branch](https://github.com/elementary/appcenter/pull/1563) causes Dippi not to appear

However, it does appear in the category view as a curated app

**Comment by davidmhewitt** [comment]
The `is_native` flag simply checks the package origin, which in the case of a Flatpak package, is the remote name.

So if your `Package` is a Flatpak of Harvey from flathub, then I genuinely feel that `is_native` should return false, because it's one of the checks that determines whether payments should be enabled or not. So if it's been packaged on flathub with a stripe key, and we return `is_native` for a package just because it's available from AppCenter too, then I think there's a potential for problems.

We'd end up enabling payments for that version on flathub, that may have someone else's stipe key, may not even be the same app, may not be the latest version and/or may be broken by patches. So I'll close this issue for now and leave some feedback on your PR.
