### ISSUE TITLE
Page view keeps scrolling even though iterating through screenshots

### ISSUE THREAD

**Issue by kdwk** [elementary/appcenter#1578]
## What Happened

https://user-images.githubusercontent.com/39268094/128486128-a63a24aa-828d-4715-b3a6-7e4689a45353.mp4

## Expected Behavior

The page should stop scrolling when the mouse is hovering over screenshots and is scrolling, so that the user can view the screenshots uninterrupted.

## Steps to Reproduce

1. Open an app
2. Scroll down to screenshots
3. Hover over screenshots
4. Keep scrolling

## Platform Information

AppCenter 3.6.1+r3002+pkg101~daily~ubuntu6.1

**Comment by cassidyjames** [comment]
Rather than hijack scrolling, the solution I'd like to see is to disable vertical mouse wheel scrolling on the horizontal screenshots. We have pager buttons, horizontal scroll support, and swipe support, but scrolling down the page shouldn't be interrupted; this is how this is typically implemented on the web as well, for example.

We're blocked by the release of Handy 1.3, which should be coming along with GNOME 41 in ~a month.
