### ISSUE TITLE
bcmwl-kernel-source not installed correctly from AppCenter (WiFi on MacBooks)

### ISSUE THREAD

**Issue by supaeasy** [elementary/appcenter#1603]
It took me some time to check this out, maybe it is obvious but:
When bcmwl-kernel-source is available in AppCenter (MacBooks, maybe other laptops as well) it will not install successfully (altough it will say so). You will have to first install Linux Kernel Headers via Terminal and then you can use AppCenter to install these drivers. 

Steps to take:

```
sudo apt update
sudo apt-get install linux-headers-$(uname -r)
```
After this, visit AppCenter and install drivers from "Installed" Tab. WiFi will work now.

This is the solution already, I just leave this open so you might consider installing kernel headers via AppCenter or automatically before for a better user experience. Having a clean installation with no WiFi is annoying.

**Comment by davidmhewitt** [comment]
After looking into this a bit more, it seems to be an Ubuntu issue.

The `bcmwl-kernel-source` package depends on the kernel headers for kernel 5.4, which is the non-HWE kernel. So, even if you manually install that package or do `sudo ubuntu-drivers install`, the exact same thing happens. And I suspect the exact same thing would happen if you were running Ubuntu natively too.

I'll leave this open as it's possible we can try and make this a bit more friendly by detecting this situation and automatically installing the right kernel headers too.

For reference, it would be better to install `linux-headers-generic-hwe-20.04` instead of `linux-headers-$(uname -r)` as this will ensure that you get updates to the headers going forwards when new kernels are released.

**Comment by supaeasy** [comment]
Thank you very much for looking into this!

**Comment by katiehartrick** [comment]
I had the same issue with a clean install on a 2013 MacBook Air. The install above did not work. Instead I used:

` sudo apt install firmware-b43-installer`

**Comment by tallthom** [comment]
While installing 7.1 I also encountered this issue. Its a little like chicken-egg because you want to install the driver, but you don't have internet on the MacBook Air 2013 -- there are no LAN ports so I'll need to plug in a USB lan port to get the driver. If the driver was available on the installation media, then it could be added if the user selects it. This might make some users give up on elementary...
