### ISSUE TITLE
Make user aware of flatpak add on to the app centre

### ISSUE THREAD

**Issue by diddy-boy** [elementary/appcenter#1635]
Would be nice if there was either a guide on the welcome screen or some textual guidance to the user that they can extend the app center capabilities by adding flatpak through side loading an app by clicking on the link :-

https://flathub.org/apps

## Problem
I spent a few days thinking the app centre was lacking, then found from another youtuber that the app center is actually really powerful once a flatpak app has been added

## Proposal
add either a screen / page on the welcome app that the app center can be enhanced by adding flatpak 
or add a toggle option on the app center to add in flatpak apps
or have some text on the app center with a link off to flathub

I am sure I am not the only user wondering this so how many people start using Elementary OS, find the app center lacking and move on to another distro ?
you could be missing out on users that would stay if they at least knew of flatpak support or had it built in with a full app listing out of the box.

thanks

Rich

**Comment by danrabbit** [comment]
Hey thanks for your feedback! We currently include language in the Onboarding app about sideloading apps and directly reference Flathub there. We've also recently adding language to the search view that mirrors this in AppCenter. We also include language in Sideload indicating that sideloading an app may show other apps from its remote. And as you've noticed we rely on the tech press to help make users aware of features as well as highlighting them on our website, blog, and social media.

I'm not sure we want to direct users specifically to Flathub any more than we already do. Flatpak is decentralized technology and we want to make sure we're treating 3rd-party remotes fairly equally.

I'm going to close this issue since we already include language in Onboarding, Sideload, and AppCenter about this feature
