### ISSUE TITLE
Extend app center with popular applications for everyday use

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/appcenter#2012]
### Problem

Consider the case where elementaryOS might be used for a school laptop etc. in a school etc.
The users (usually younger people) will not necessarily be familiar with installing software from the command line.
They might to just want to use the PC for everyday tasks and are already familiar with a certain web browser.

It would be good if it were very easy for them to install that browser.
I guess most users would start looking in the App Center as the first try.

They might immediately get disappointed because currently, it is not possible to get Firefox etc. via the App Center (at least not on a vanilla install of elementaryOS 7)

### Proposal

Add apps like Firefox, Thunderbird, Chromium, Google Chrome, Libreoffice etc. to the native elementaryOS appcenter so that unexperienced users can find them using the search bar.

**Comment by danirabbit** [comment]
Thanks for your report! Unlike traditional Linux distributions elementary does not re-package 3rd party apps. AppCenter operates on an App Store model where developers submit their apps to be published there. If you want the developer of a specific app to publish their app in AppCenter, please ask them to do so :) 

In the meantime, you can easily side load apps from any Flatpak ref file or from alt stores like Flathub. I believe that Mozilla does publish their Flatpak of Firefox on Flathub.org so that would probably be the place they would recommend to download it from.

Closing since this is out of scope for AppCenter since elementary doesn't re-package third party apps and it's up to developers which stores they choose to publish their apps in

**Comment by CodingSpiderFox** [comment]
I doubt that a large portion of developers would be willing to package their app for the elementary app center or other app centers because that would mean additional complexity in the publishing process of their apps.

I want to advocate for a "normal" user's point of view. When you just start exploring a new distro as someone who just starts learning to use anything else like windows or mac os.
Almost all of them might start looking for their favourite apps in app center
