### ISSUE TITLE
Cache banners [$80]

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#210]
That way you theoretically only see the placeholder once and then we update from the last cached set

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/43879325-cache-banners)

**Comment by cassidyjames** [comment]
I brought this up at https://github.com/pop-os/shop/issues/177#issuecomment-620175312, but this is a little more thought out:

- Create a GSetting for the results of the different API enpoints
- Hit the API. If it takes longer than expected (or fails), fallback to the GSetting contents
- When hitting the API, cache those IDs in the GSettings for future use

Because we want the homepage to stay fresh, we should still default to hitting the API. But I occasionally we see server issues or a poor Internet connection making the API call fail, and right now we just don't show anything when that happens. This would at least mask over those issues while still keeping things fresh.
