### ISSUE TITLE
Accept Bitcoin

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#229]
Stripe supports this, so it should be possible right?

**Comment by danrabbit** [comment]
Not sure what about this needs design. I think we'd just follow the Stripe Connect design here again

**Comment by btkostner** [comment]
This might be _a lot_ harder than what it seems. Right now with credit cards, the charge can be instantly verified and we can continue on our way. With bitcoin, you make the request, get an address, then at some point in the X minutes after the funds are transfered, the charge can actually be made.

Usually this process is seen as a (processing transaction) status in online stores. Because we are doing some fancy desktop app work, this will be interesting...

**Comment by danrabbit** [comment]
Yeah, and honestly the experience with BitCoin on our website has left a bad taste in my mouth. The experience is bad for users. Transactions get rejected because fee bidding fails. It's a bad time.

**Comment by parnold-x** [comment]
Bitcoin Core is dead for payment. If you do it use Bitcoin Cash.

**Comment by btkostner** [comment]
If we did bitcoin, it with be with Stripe. As far as I know Stripe only accepts BTC.

**Comment by parnold-x** [comment]
Maybe, but then you can just drop it. Bitcoin is at around 70-80$ fees at the moment if you want to let it clear in less that a couple of hours.

**Comment by davidmhewitt** [comment]
Stripe is going to stop supporting bitcoin so I think we can close this now:
https://stripe.com/blog/ending-bitcoin-support
