### ISSUE TITLE
Expose non-curated app remote

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#233]
I've heard from a couple folks that they want a way to know which apps were made for elementary OS. While we still have apps from the Ubuntu repos, perhaps we need a way to mark those apps so that people know that they are not from our repos.

**Comment by cassidyjames** [comment]
@danrabbit I presume @elementary/ux will need to come up with some sort of design for this, or did you have something in mind?

**Comment by danrabbit** [comment]
Yeah needs design

**Comment by cassidyjames** [comment]
Possibly terrible idea incoming :stuck_out_tongue: 

Would it be super obnoxious to badge the icon with an Ubuntu logo, and maybe have a tooltip on it that says "From Ubuntu repositories" or something?

**Comment by cassidyjames** [comment]
Now that we have https://github.com/elementary/appcenter/issues/319, I wonder if a `Non-Curated` badge of some sort would be enough? Then we keep the string the same while ensuring users still see it if they arrived at the app listing from a Slingshot search or appstream URL.

**Comment by cassidyjames** [comment]
i.e. something like this 
![screenshot from 2017-05-25 11-30-47](https://cloud.githubusercontent.com/assets/611168/26462359/abf98266-413d-11e7-92a2-8e02bbd10df2.png)

**Comment by davidmhewitt** [comment]
I wonder if this is still relevant 2+ years on, especially with the recent non-curated dialog?

**Comment by cassidyjames** [comment]
@davidmhewitt I think it is actually. We realized that there's no way to tell which remote an app is coming from unless there's the same package ID coming from multiple remotes. It shouldn't require the intent to install just to know that. 

I think instead of that “Non-Curated” badge, we could put the remote name in a label where the combobox goes when there's multiple remotes. i.e. if there's one remote, show the label, if theres' 2+, show the combobox.

**Comment by cassidyjames** [comment]
@danrabbit I wonder if moving it more inline with the developer name would make sense? We seem to generally have more horizontal space to work with than vertical. i.e. single remote:

![IMG_20191107_193800](https://user-images.githubusercontent.com/611168/68445325-d5af9e80-0196-11ea-83b6-184a5b6694ad.jpg)

multiple remotes:

![IMG_20191107_193831](https://user-images.githubusercontent.com/611168/68445324-d5170800-0196-11ea-8301-3370b6a5e6ae.jpg)

**Comment by cassidyjames** [comment]
Then I guess that raises the question of, what do we put for our remote? “AppCenter” could be confusing because all apps are in AppCenter. So what about “Curated :heavy_check_mark:” or something to show that it's trusted? Kind of like when I see “Editor’s Pick” apps in Google Play.

![IMG_20191107_194522](https://user-images.githubusercontent.com/611168/68445627-a8afbb80-0197-11ea-9e46-1d3938b75456.jpg)

**Comment by cassidyjames** [comment]
We've been discussing a lot on Slack related to #1185.

Sketch and early prototype ideas from @danrabbit:

![73094554-a48d6300-3e95-11ea-9fcb-0e4a548d6067](https://user-images.githubusercontent.com/611168/73097116-9e9e7e80-3ea3-11ea-8d22-7a7914b22f22.jpeg)

![Screenshot from 2020-01-24 11 11 24@2x](https://user-images.githubusercontent.com/611168/73097128-a78f5000-3ea3-11ea-8844-2ae33e3fe1ef.png)

Ideas for a design iteration:
- [ ] Show "distributor" below app name. For curated apps, we have verified authors so we can just show the author name. But for all other apps, we show "Ubuntu" or "Flathub" or whatever.
- [ ] Badges in the content area below the header for "Non-Curated", license, content ratings, etc.
- [ ] For apps with multiple origins, we could move the origin dropdown to the left of the footer (it's incidental, since we should show the "right" origin package the majority of the time
