### ISSUE TITLE
Display the sizes of Apps before download

### ISSUE THREAD

**Issue by yeboahnanaosei** [elementary/appcenter#411]
Show the user the size of the app before downloading. This will be extremely helpful for users on metered networks or users with limited data plans

**Comment by yeboahnanaosei** [comment]
Adding a mockup. 
@cassidyjames : See the download size under the "Free" button? That's how I conceptualize it.
<img width="1293" alt="appcenter-downloadsize-mockup" src="https://user-images.githubusercontent.com/22800157/29524719-1acf32ee-8680-11e7-89d0-83ccfa73f99a.png">

**Comment by peteruithoven** [comment]
Why so big and bold? 
Do we have data on how large the group is for whom this is that interesting? If it's only interesting for a minority it might be more appropriate to place it in the footer, maybe next to the license?

**Comment by yeboahnanaosei** [comment]
@peteruithoven. I agree. More discussion needed though. I will apply a few changes and see how it will look like

**Comment by yeboahnanaosei** [comment]
Nothing significantly different. Made it way smaller than the earlier mockup.
I feel whether you are on a metered network or not, knowing the size of the app is still an important piece of information to know about the app before downloading; hence the reason why I put it at a very visible spot. However, the discussion must still go on.

![downloadsize-mockup](https://user-images.githubusercontent.com/22800157/29530316-a5200092-8692-11e7-83e4-4ffba7738733.png)

**Comment by yeboahnanaosei** [comment]
Nothing significantly different. Made it way smaller than the earlier mockup.
I feel whether you are on a metered network or not, knowing the size of the app is still an important piece of information to know about the app before downloading; hence the reason why I put it at a very visible spot. However, the discussion must still go on.

![downloadsize-mockup](https://user-images.githubusercontent.com/22800157/29530316-a5200092-8692-11e7-83e4-4ffba7738733.png)

**Comment by danrabbit** [comment]
The actual size of Metronome is 76kb. Depending on the app, you'll use more data to show screenshots than to download the app itself.

**Comment by cassidyjames** [comment]
For the AppStream side of this, we'd probably want to show the latest release's size? In which case, there's an optional `size` tag for releases: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

However, this doesn't completely make sense because we'd either have to generate the size when building the app, or expect developers to hand-update this. Both of which seem like a huge pain. Plus that would effectively make it packaging dependent, and so useless in other AppStream data consumers.

Are there other mechanisms for getting the download size of the app?

**Comment by samrocketman** [comment]
As someone whose family lives in a rural area and who is occasionally on mobile internet, download size does matter.  Knit picking over this guy's mockup isn't really productive.  It's easy to take for granted something like this when you're in a city with a near limitless ability to download data.

I expect a mockup to give "an idea" and help make it more clear.  That doesn't mean elementary won't go through their own UI/UX process to ensure the experience remains good.

**Comment by davidmhewitt** [comment]
So the difficulty here isn't knowing how big the .deb download is, we can get that information through PackageKit. The size field of a Package is its download size if the package is not installed:
https://valadoc.org/packagekit-glib2/Pk.Package.size.html

References:
https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/apt-intf.cpp#L725-L730
http://charette.no-ip.com:81/programming/doxygen/libapt-pkg/structpkgCache_1_1Version.html#a598bea458adc7dc527b2f8da6d7217bb

The difficulty is figuring out the total size of the download that happens when you click the install button. So that includes the total size of the package and its dependencies.

It's probably possible to figure this out, but you'd have to do the following:
* Get a list of the dependencies of the package and hope PackageKit does the right thing and gets dependencies of dependencies, etc...
* If those dependencies are already installed, throw them out of our calculation
* Add up the total download size of the non-installed dependencies plus the size of the package

Et voila.

That's not an insignificant amount of work, which is probably why nobody has done this yet.,

**Comment by samrocketman** [comment]
I think it's reasonable to display a worst case with a star *.

> `*` actual download may be smaller if some dependencies are already installed.

This can avoid overcomplicating the feature.  Since the package list is curated, I would also think that total package size can be precomputed for all packages and stored in a datastructure of the application (maybe a JSON blob).
