### ISSUE TITLE
Indicate if an app is localized in your language

### ISSUE THREAD

**Issue by danirabbit** [elementary/appcenter#440]
GNOME Software has a neato feature of showing if an app is available in your language. We should have that too

**Comment by yeboahnanaosei** [comment]
Hi Dan, do you mean **_neat_**?

**Comment by danrabbit** [comment]
Gonna punt this feature since we're already end of April

**Comment by davidmhewitt** [comment]
An update on this:

In gnome-software, this data comes from a bunch of tags in the appdata that look like this:
```
  <languages>
​    <lang percentage="96">de_AT</lang>
​    <lang percentage="100">de</lang>
  </languages>
```

These tags should be automatically generated and added to the appdata by `appstream-generator` _if the application specifies its gettext domain_ in it's AppData.

I've submitted a branch to calculator to add this so we can see if appstream-generator does indeed do this:
https://github.com/elementary/calculator/pull/124

Then we'll need to go around adding that to everything and recommending that third party developers do the same.

**Comment by davidmhewitt** [comment]
Another update, the version of `appstream-generator` we're using for 1st party apps is not new enough to generate the needed data. Since this is all done in docker/Github Actions, we could use focal images to get a newer version, but it seems `appstream-generator` is currently broken in focal. Bug here: https://bugs.launchpad.net/ubuntu/+source/appstream-generator

So I'll mark as blocked for now.

Once this data starts becoming more widely available, we'll need some design input to figure out how best to display this.

**Comment by danirabbit** [comment]
It looks like we do now have `lang percentage` tags in our appstream data for AppCenter
