### ISSUE TITLE
Ship a policy file that allows installing apps by default without throwing the password dialog [$30]

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#465]
Because otherwise if we're password protecting payment information then we need to throw auth twice when installing apps and that's shitty

---
There is a bounty on this issue on [Bountysource](https://www.bountysource.com/issues/48656323-ship-a-policy-file-that-allows-installing-apps-by-default-without-throwing-the-password-dialog)

**Comment by Philip-Scott** [comment]
As long as only AppCenter can make use of it and only for our apps sounds good. otherwise, being able to install things with apt or whatever without sudo sounds like a security hole to me

**Comment by danrabbit** [comment]
Gonna punt since this is an enhancement not a release blocker

**Comment by cassidyjames** [comment]
We talked about this in standup today. We should be good to install all Flatpaks without auth because the only system Flatpak remote by default with be a first-party elementary one, and adding remotes is a user action by default with Sideload. If an administrator adds a Flatpak remote as a system remote, they have to go out of their way to do so and then users will be able to install any apps from that remote without auth.

On the PackageKit side, we should allow updating without authentication, but still require it for new package installation.

**Comment by davidmhewitt** [comment]
Closed in #1305
