### ISSUE TITLE
request: GTK-themes optimized for elementary OS in AppCenter

### ISSUE THREAD

**Issue by capstan1** [elementary/appcenter#469]
It would be handy to be able to publish (and install) themes via AppCenter. Some people will always want to change appearance of their DE in the Linux world.

There are many advantaged of curating themes in AppCenter:
- only themes developed for elementaryOS will land there and users will prefer these, wich will result in less problems
- this might bring less complaints about things not working correct (by people using themes - that are not meant to be used with elementaryOS - )
- wider range of "items" in AppCenter
- giving theme-developers the possibility in participating in your pay-what-you-want vision
- installing themes would be easier
- there already exist some great themes for elementaryOS and this will empower people to develop more good themes -> point 3
- it makes the OS feel more complete (at least for me - eg. I really liked the option of installing themes in KDE via system-settings)
- updates of themes without adding untrusted ppa's to your system

I know the team is not a big fan of too much customization, but the OS should deliver options, so the users can get their perfect OS. If I feel in need of a bit more color, it's nice to get it and to not be left with only one choice. Also you could apply the same to apps: why allow an System-Monitor app, if we already have a system-application for that? Because of choices.

Although I understand your points, please consider my suggestion.

**Comment by cassidyjames** [comment]
There are not plans to ever officially support arbitrary stylesheets in elementary OS. Even if the stylesheet author claims compatibility with elementary OS, there are so many apps being developed with custom styles that assume the elementary stylesheet will be used that you're bound to run into problems constantly. The stylesheet is considered part of the stable platform and its API.

We could theoretically require app developers to develop against and test with every possible stylesheet, or we could impose strict limits with what developers are allowed to do in order to be more generically stylesheet agnostic. Neither of these options are practical, nor would they go over well with developers.
