### ISSUE TITLE
Don't install unpaid apps when clicking "Update All"

### ISSUE THREAD

**Issue by danrabbit** [elementary/appcenter#502]
Relies on #306 

Trying to think of a fair way to "nag" people about paying for the apps they've previously downloaded for free:

A user downloaded an app that is a suggested price of $1 for free. A week later there's an update for the app. When the user visits the updates page, they click update all.

Instead of installing all updates, AppCenter should only install updates which are either free or already paid for.

Apps which have not been paid for should display their suggested price and require the user to either pay or once again enter $0 to get the update.

In this way, users can still choose not to pay for the apps, but it becomes less convenient not to pay. At this point in time, we can probably assume that the user is getting value from the app and it's a fair time to re-prompt them to support its development

**Comment by valkirilov** [comment]
+1 Sounds fair for the developers.

**Comment by cassidyjames** [comment]
I'm in favor of this as well. It doesn't make it impossible to get and continue using monetized apps without paying, but it definitely directs users toward paying the dev.

**Comment by cassidyjames** [comment]
@danrabbit something I just thought of: how do we handle paid, but below the suggested price? Do we just lump them into paid, or unpaid?

**Comment by cassidyjames** [comment]
We could also store the amount paid on the user's machine, and if it's below the suggested price, re-prompt for payment on update? Maybe do something clever about prompting for the difference between what they paid and the suggested price?

That might be over-complicating it, and it would have some interesting implications for an increased suggested price as well…

**Comment by Thalexander** [comment]
By making it less convenient to update this may make users less likely to update and so they may not get security fixes as fast leaving them exposed.

**Comment by danrabbit** [comment]
@thalexander since this only applies to applications and not libraries or the kernel there shouldn’t be any security implications here.

@cassidyjames I think we should count any amount as “paid”. One of the strong talking points we use for pay-what-you-want is that users can choose a price they can afford or think is fair. If we bug them about paying after they’ve already chosen a price it feels like we’re not holding up our end of that contract, imo

**Comment by cassidyjames** [comment]
@Thalexander that may be true, but apps should also not be shipping critical security components; updates to system libraries and OS components would still be updated as normal.

**Comment by cassidyjames** [comment]
@danrabbit that's a good point. I wonder if we should still store the amount paid locally for future use, like having an overview screen that shows amount paid or something. But regarding the update prompt, still count any nonzero amount as paid.

**Comment by danrabbit** [comment]
That’s an interesting idea. We could perhaps use it as a way to gamify and show a leaderboard or something

**Comment by valkirilov** [comment]
I don't think that it's a good idea to keep the data about the payments only locally. 
For example I could use elementary OS on a few computers, not only one. Also.. I could reinstall elementary OS and this way I'll lost the information about my payments.. behaviour that is not so cool.

**Comment by cassidyjames** [comment]
@valkirilov of course, but that's a whole separate issue with much larger implications. A first step would be to store the info locally.

**Comment by djsmithumn** [comment]
@danrabbit there is strong evidence in behavioral economics research suggesting the using an opted-out payment scheme instead of an opted-in payment scheme would increase payments. Giving users the option to opted-out and pay $0 still allows users to express their preferences. In addition, a one-click payment scheme, that takes about the same amount of time to pay as it does to enter $0, is probably needed to make payment prompting on update a success.

**Comment by nan0s7** [comment]
Hey, just thought I'd add an idea and my opinion to this thread. I like this idea, but it'd be nice to be able to "postpone" that app payment. For example, instead of just entering $0, the user is able to tell the Store that they would like to pay on a later date, and would appreciate a reminder as well. I'm not saying that it should just deduct the amount from the users current payment method, but give them another notification in a few days/weeks so they can donate/pay for the application then. As much as I love supporting developers (especially for "free" software), sometimes I just need all the money I have and would much rather pay (possibly even more than the asking price) on another date when I have more money to spend on hobbies and such, or just when I feel more comfortable with my bank balance.

On the flip side of the issue, it would be nice to be able to turn off the "bugging the user to pay for something they said they didn't want to pay for at the time" feature somewhere. For those, it may be interesting to have an area of the Store that shows all the applications that the user hasn't paid for. Almost like a shopping list. A... more passive reminder. I feel like a lot of users will be put off by the nagging upon an update, but I also want the developers to get paid for their hard work. I feel like if the user can choose when to pay, rather than being asked for payment, that would lead to the user to be more generous in the long-term.

It's certainly an interesting proposition.

**Comment by JonnyCodewalker** [comment]
Speaking of personal experience, I would be careful to not make it too annoying. Many Apps might get smaller Updates 2-3 times a week.  Having to enter the 0 multible times a week would maybe prompt users to seek for another alternative or avoid updating all together. 

My suggested solution would be doing it at the first Update after a week (or two) and then again whenever an app has a major release. This way they get reminded the first time after a time of use where you can reasonably assume them to keep it. But at the same time it would (considering how "rare" major updates are) not be to much to turn them away from updating/using AppCenter apps.

A idea for multible platforms would be an "already paid" Option when downloading, either trust based or proof based, so that people don't feel like they are pushed to paying multible times.

**Comment by cassidyjames** [comment]
Yeah @danrabbit, @JonnyCodewalker has an interesting point. Can we use [semver](http://semver.org/) to be smart about when to prompt for payment? Maybe just major or major + minor versions, but not patches?

**Comment by danrabbit** [comment]
Yeah but I think that would just punish developers who don’t know about that mechanic and reward those who exploit it

**Comment by JonnyCodewalker** [comment]
In prevent punishing developers you could explain semver in the getting started guide. Against the exploiting the only thing I can think about is not allowing non-patches to often, wich would result in quite a few problems or, and this is what I would suggest, combining it with a timer so that only every major/minor every X weeks coutns towards promting payment.

**Comment by danrabbit** [comment]
It would probably be more effective to have some kind of throttling than to try to divine anything from the version number. But, my personal perspective is that being inconvenient is the entire point ;p

**Comment by JonnyCodewalker** [comment]
It is, I am just worried that making it too inconvenient would hurt more than help :P

**Comment by bigfatbird** [comment]
I don’t think it’s a good decision to bug me about payments while I want to update my software. 

If I hit update my computer should do one thing and nothing else: Update!

**Comment by donadigo** [comment]
Here's my take on this:
While it is nice that people will have a way to pay for apps that got an update, "update all" doesn't do what it says anymore.

The reason why "update all" exists is that people want to _quickly_ deal with the updates and get back to their stuff. Prompting them with another dialog everytime or disabling the "update all" button perhaps will make them acknowledge that they could pay, but lots of other people that don't want to pay or simply can't afford to, will completely _stop_ using AppCenter for updates. From there, everytime they will see a notification about an update, they won't open AppCenter, but open the terminal and update with `apt upgrade` because they saw an article that said to do that to update their system quickly.

We need a balance between user and developer, we want to pay developers but also we don't want to make user's life _too_ unconvinient while encouraging them to pay.
