### ISSUE TITLE
No descriptions for updates

### ISSUE THREAD

**Issue by banerjeesamrat** [elementary/appcenter#549]
I think it would be more reasonable to provide update descriptions for the updates in the appcenter whether it be os updates or third-party app updates as it will help the user understand what the update is doing and he/she can exploit the benefits of the update.

I think this is a an urgent issue that needs to be focused on.

**Comment by danrabbit** [comment]
AppCenter already supports release descriptions, but it's up to each component to provide their own. We're currently only warning developers to include release descriptions with updates. In the future it will be a requirement, but we're in a transition period to allow everyone to adjust.

Closing since this is as fixed as it can be inside AppCenter's codebase
