### ISSUE TITLE
App Center would randomly stop getting updates until reinstall.

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/appcenter#551]
App Center randomly stops installing updates even though it fetches the list of apps to update. Running apt-get upgrade or apt upgrade would show some package like gcc or dpkg update not installing due to hash sum mismatch.  This also prevent updating software via terminal and shows the same error.

**Comment by davidmhewitt** [comment]
If `apt` is unable to perform updates in the terminal because of hash sum mismatches, then this isn't a problem with AppCenter. It sounds like the repositories you were trying to update from were misconfigured or synchronizing.

There's nothing AppCenter can do here if the underlying package manager isn't working either.

I'll close this issue, but if you have any further details that you feel are relevant, feel free to add them to the issue.
