### ISSUE TITLE
Adding Godot Engine to the Development category 

### ISSUE THREAD

**Issue by Mikerr1111** [elementary/appcenter#587]
I was looking at the latest release of the open-source game engine Godot 3.0 and it looks really good https://godotengine.org/article/godot-3-0-released. As someone who does game development in the open source community, I find value in having this in the elementary AppCenter.

**Comment by memnoth** [comment]
There is no PPA for Godot engine yet that be able to install with command, like ``apt install godot``.
The official site also offers a best and portable way to install it in your **home** directory.
It is more easy than installing into system path, /usr/bin or stuffs like that.

**Comment by Mikerr1111** [comment]
Yeah, I understand that.

**Comment by danrabbit** [comment]
Hey thanks for your suggestion. Unfortunately this is not fixable within the scope of AppCenter. All app metadata (stuff like categories) comes directly from 3rd party developers. The developers of Godot would need to provide an appstream metadata file with their package and then submit it to be published themselves. elementary doesn't package 3rd party software on the behalf of other developers.

Closing as "Out of scope" since this can't be solved within the AppCenter codebase

**Comment by mrnhmath** [comment]
@Mikerr1111 it's likely that Godot will show up in AppCenter if it gets packaged for Ubuntu 18.04 repos, which elementary OS Juno will be based on.
