### ISSUE TITLE
Ignore / skip broken ppa's?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/appcenter#596]
Even though elementary OS discourages adding third party ppa's, they still will. Not every app is in the AppStore and most apps don't offer other solutions like snaps, flatpack or AppImage, so this is not going to change soon. [/rant]
Currently when a ppa breaks, the user can't update anything anymore. He'll most likely need to go into the terminal to fix it. 

Isn't there a way to ignore / skip ppa's with issues? To prevent users from permanently disabling ppa's that have temporary issues we should probably re-ask this for every update? 

I'm afraid that allowing users to disable the ppa outright with the press of a button is a bit to easy for something that could cause issues later on. But I'm curious about other people's opinion on that. 

For the error to be understandable we should probably show the app names there where installed by the ppa. The ppa itself isn't always that clear.

**Comment by lewisgoddard** [comment]
The best solution might be to just comment out any source list lines (not necessarily PPAs) that cause errors, with exceptions for the defaults. This would need to know that the sources weren't failing for some reason like no internet connection though.

**Comment by danrabbit** [comment]
As far as I understand it’s sctually packagekit that throws a fatal error for broken software sources, so this would have to be fixed there

**Comment by peteruithoven** [comment]
Good point, but I'm afraid I know to little of it's api to open a useful issue.
I understand Packagekit is a layer on top of package managment tools like apt. I think the AppCenter talks to it using [packagekit-glib2](https://valadoc.org/packagekit-glib2/index.htm). 
Ideally it's `refresh_cache_async` method would throw errors from which we could identify a repo and ignore that repo in a next `refresh_cache_async`? This could then be repeated until the cache is refreshed successfully? 
It does seem to have methods to enable / disable repo's: https://valadoc.org/packagekit-glib2/Pk.Client.repo_enable.html

**Comment by davidmhewitt** [comment]
I've been looking into this and found that the PackageKit error information isn't granular enough to determine which repository is causing issues without too much hacky string parsing and enabling/disabling repos needs admin authentication, so a password prompt in the middle of an error is likely to be confusing/scary.

Discussing this in Slack we came to the conclusion that we're never going to be able to do this safely/reliably enough for it to be worth doing.

The error dialog already says that it's likely an error "caused by external, manually added software repositories or a corrupted sources file". So we already give a pointer in the direction of what went wrong so the user can fix it.

**Comment by peteruithoven** [comment]
Would it be usefull to open an issue against the PackageKit library? Or is the plan to just focus on Flatpak?
(It is probably true that with flatpak and snap people have less neat to use ppa's)

**Comment by davidmhewitt** [comment]
I think this isn't exactly trivial to be solved in PackageKit either because of the way apt reports errors. There's also not a huge amount of effort being put into maintaining PackageKit these days so I doubt it would gain much traction.

We've definitely been seeing slightly less people reporting issues with PPAs since we starting pushing and supporting Flatpaks.
