### ISSUE TITLE
Collapse non-curated list

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter#609]
If we have non-curated apps in a list, we should collapse them under the header. This deprioritizes them without straight up removing them from AppCenter.

Something up for discussion is if we want to _always_ collapse them, or only when there are curated apps in the same list. I imagine the latter would work best with downstreams and for search results where there are no curated apps.

**Comment by danrabbit** [comment]
I'm gonna punt since this is an enhancement and not a release blocker

**Comment by inputbim** [comment]
seperate category in appstore to only see curated apps? hard to discover curated apps without going to the website

**Comment by matfantinel** [comment]
I think it's worth considering if this should be applied to all uncurated apps regardless of source (Ubuntu repos, Flathub, etc) or just to the .deb ones. Since Flathub is a source to many well-known apps like Slack, Spotify, and soon Firefox, and Flatpak provides an extra security layer, maybe it's okay to keep them displayed below the curated ones. Specially considering the user has knowingly added these sources manually via Sideload, unlike the Ubuntu repos

**Comment by cassidyjames** [comment]
I'm still inclined to treat them the same as other non-curated apps. On elementary OS today, there are not that much stronger of security guarantees, as we're still using Xorg and thus these apps still aren't sandboxed.

**Comment by danrabbit** [comment]
Closing since we don't show apps from Ubuntu in the default install and if someone adds a remote we shouldn't hide the remote that they intentionally added
