### ISSUE TITLE
Show indicator when AppCenter is running in background

### ISSUE THREAD

**Issue by jwinnie** [elementary/appcenter#673]
When AppCenter runs in the background, APT cannot be used from the command line and the system slows down a bit. As such, there should be an indicator in the panel when it is running and an option to stop it.

**Comment by cassidyjames** [comment]
AppCenter's PackageKit backend uses apt under the hood, as expected. Since apt cannot perform multiple operations at one time, this is expected behavior. Most users should be using AppCenter to perform updates and installations, and if they're using Terminal, they are likely savvy enough to know how to stop other processes that might be using apt.

I don't think adding extra UI to the panel that encourages people to stop updates in the middle of package operations is something we'll ever want to do.

If PackageKit, apt, or AppCenter are unacceptably slowing down the system when running, those would be separate issues.
