### ISSUE TITLE
appcenter fails to update repositories

### ISSUE THREAD

**Issue by argenisaz** [elementary/appcenter#681]
Every time I open App Center it fails to fetch updates do to repositories not having a valid publishing date. Installing updates is not possible. I haven't installed ppa's manually, all software installed comes from App Center. I believe the same message is given when I run sudo apt-get update, but at least it's possible to upgrade some apps.

**Comment by davidmhewitt** [comment]
I'm cleaning up the issue tracker and I feel it's best to close this issue due to age and no similar reports. Sorry that nobody followed up with you to investigate. If you're still an elementary OS user and are still experiencing the issue, please feel free to re-open the issue and include the actual error text or a screenshot.
