### ISSUE TITLE
[BUG] Error in Midori Uninstall/Install

### ISSUE THREAD

**Issue by btd1337** [elementary/appcenter#717]
I'm not sure if this problem should be reported here but this error occurs while trying to uninstall/install the Midori browser in the AppCenter.

![captura de tela de 2018-05-25 13 11 40](https://user-images.githubusercontent.com/11943860/40554965-d9b82180-601d-11e8-8ab0-fd1c589f63cd.png)

**Comment by danrabbit** [comment]
This is a problem with Midori's appdata. This seems to be a mistake where the appstream generator thinks that Midori's private browsing .desktop file is its own app.

This can't be fixed within the context of AppCenter since this app isn't responsible for generating Midori's metadata. Closing as "Out of scope"
