### ISSUE TITLE
Consider not requiring NetworkManager as a hard depenency

### ISSUE THREAD

**Issue by brs17** [elementary/appcenter#765]
Consider not having a hard dependency on NetworkManager. This would allow someone to use wicd or whatnot and not have to configure/use NetworkManager just to get appcenter to get a network connection.

This issue was filed downstream for the Pop!_Shop here: https://github.com/pop-os/shop/issues/83

**Comment by danrabbit** [comment]
I think I'm going to close this issue as "Out of Scope" as it's not inside the scope of AppCenter to manage networks. That's why we have services like NetworkManager is to make sure we aren't implementing the same code  in our apps and we have a canonical source of truth for things like network status. I think it's reasonable to expect that the system networking service is running.

**Comment by foowhat** [comment]
Having also come across this issue as well (but with Elementary, not POP) I'm confused by @danrabbit's response. Though please let me know if I'm simply misreading it. English is not my native language and it's quite possible that his reply meant the check is becoming generalized rather than specific. :)

While it's reasonable to expect the system network service is running, wouldn't it be even more reasonable to not do any sort of check for a specific network service daemon/whatever? 

I realize those of us who either temporarily or permanently switch away from NetworkManager are an edge case, but at least for me it stopped me from being able to use Elementary on my work laptop because it added an extra step to my workflows as I'd have to remember to stop wicd and all of my work related networking tasks, start NetworkManager, complete whatever five second appcenter task I wanted to do (I like to browse!), stop NetworkManager, restart my work stuff, rinse, repeat.

**Comment by danrabbit** [comment]
@foowhat The thing is that we want to make sure we're providing useful error messaging to our users. If a user is unable to install a package we need to know the difference between the computer being offline and that server being offline in order to give good advice. If there was some freedesktop dbus interface to subscribe to for network status I would be happy to switch to checking against that instead of against network manager specifically. As far as I know though, that isn't a thing that exists so we're using the API that is provided by the system's default network manager. I think you should expect that if you change out core components (like the network manager) that some things will not work properly

**Comment by mutech** [comment]
I came across this six years later and feel like it really deserves some reconsideration.

I'm not using network-manager for wired connections on my laptop, for reasons to elaborate to go into, suffice it to say they are good reasons. So I use networkd combined with netplan (which is unrelated) but I keep network-manager for managing Wifi, because that's something it does well.

This is an edge case - sure. But it's a valid use case and a valid implementation. If Pop-OS requires the use of network-manager, it should not support systemd-networkd as well as tools that allow a user to manually configure the network. I guess nobody wants this.

So networking is a complex topic. You never know what kind of setup a computer will have. But you can know whether it works. Your operation fails with an error, just as it usually does in case of network problems (just think of network-manager being fine and some connection down the line fails, you will still get errors)

It's nice that you want to manage your users expectations about whether the shop will work when there is no network. That's for sure better than to let them try and fail. But what you do is not that, at least not in edge cases like this. You don't analyze the situation and preemptively warn the user, you actually fail to analyze the situation (there is a network connection that works perfectly fine) and not only report that misleading information to the user, you also make it impossible for the user to actually use the shop.

Worse, after updating my configuration successfully from the (in my setting) problematic default network-manager setup to a flawlessly working mixed setup, I most likely no longer received updates, because that update service (the one that consumes Gigabytes of RAM) simply thinks its offline and hibernates in its cave.

You have a point when you say that changing the core setup of a system can of course lead to unexpected problems. But is network-manager really such a core component? The system we are talking about is after all Linux and network-manager, despite it's popularity and usefulness is mostly just a convenience tool. Systemd on the other hand is definitely a core component. Systemd-networkd is an optional module thereof, but it's part of systemd and it's installed by default. 

The only way how you could validly claim that there is no network if network-manager doesn't know about it, would be to make network-manager not only a mandatory tool but also the only tool that can be used on Pop-OS to manage the network and still get support. But I think that's really not a good idea.

If you balance the benefit (preemptive warning for the mainstream-user) with the cost (make it incredibly hard for users with valid edge use cases), I think that you made the wrong choice.

After all, you could warn the user about the fact that no network is detected, which is different from "there is no network" and then just keep the UI unlocked, so that if there really is no network, the operation just fails as usual. That would achieve the same benefit but not penalized us fringe users.

Tagging you for a ping: @danirabbit

**Comment by danirabbit** [comment]
@mutech NetworkManager is what we support on elementary OS. System76 has made a quite hard fork some time ago for Pop. If you have a feature request for them you'll need to ask in their tracker. We don't support changing the networking stack in elementary OS
