### ISSUE TITLE
[Feature for OS] Libre ISO Image

### ISSUE THREAD

**Issue by asddsaz** [elementary/appcenter#797]
**Feature**: A fully Libre installation Image. No proprietary and no recommending proprietary

**Longer Summary**: The Current Elementary OS ISO asks to install 3rd party software and the app store shows proprietary software. In this ISO it would only show Libre software. Users could disable this later.

**Why**? Cuz, you are the best in the business, but many "freaks" like me hate even seeing non-free software. We believe it is a bug not a feature. 

**Why not a Libre install button?** Better security and peace of mind. :)

----------------------------------------------------
**Note**: I wasn't sure where to put this. So, I put it here cuz it seemed the most relevant.

**Comment by danrabbit** [comment]
AppCenter has no control over what goes on the ISO, so this issue is "Out of scope" for AppCenter.

I think the ideal that we'd like to work towards is a fully Open Source future, but that isn't practical at the moment and we don't intend to have multiple versions of elementary OS.

Closing as "Out of scope"
