### ISSUE TITLE
Doesn't update

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/appcenter#817]
I updated my system with appcenter.Firstly it showed that i have 6 updates and when it finished update appcenter (when appcenter finished update appcenter) than appcenter stopped update this two apps.
And I closed appcenter and reopened it but I can't click the button to update. (than I have just updated with terminal)
![2018-09-24 13-57-44](https://user-images.githubusercontent.com/26849971/45941892-0ae44600-c002-11e8-9903-2320f4faf8bb.png)

**Comment by ryonakano** [comment]
This is intentional. Apps which have suggested price do not update with "Update All" unless we don't pay for them or click the triangle and enter "0".

Please see https://medium.com/elementaryos/about-appcenter-payments-daa76a1a3b59:

> * You can still enter “0” in the custom field when downloading initially or when updating. The decision when and how much to pay is always in your hands and once you’ve paid we won’t ask again.
> * We’re not going to nag you at inopportune times. We won’t send you notifications. We won’t stop you in the middle of trying to get work done. We won’t attempt to restrict features or implement some other kind of time bomb.
> * Updates mean that the developer is providing you with additional value. They’ve spent time to make you a thing. We think this is a much more fair time to ask again than after some arbitrary time limit.
> * By not including paid apps in “Update All”, there is a bit of a convenience tax if you choose not to pay continually. We know that nag screens are inconvenient. They’re meant to be. We know that paying is also inconvenient, so we have to level the playing field a bit.

**Comment by ItsPossibleAlready** [comment]
Why developers did that. they said "Pay-What-You-Want". But finally they press us to pay that.

**Comment by ryonakano** [comment]
No, they don't force us to pay. We can use all apps for any price, including 0. If we won't pay, we'll not be restricted any features. We'll not be shown any annoying advertisement or notifications that offer to pay.

But the reason why the elementary developers did this feature is, IMO I think, just they want to let us know that paying is our gratitude for them. The developers of third-party apps spend their time thinking what app is useful and worth, and using their pooled knowledge of Vala to creating good apps to make our computing better. But sometimes they may get in trouble, may fell tired to develop, or possibly may feel ceasing developing. But they does not gave up and hereby we can use their app. I think, paying is one of our gratitude for them.

I'm not sure the actual reason for this but I think they did because they tell us something like that above.

Sorry if my reply is annoying. I just wanted to tell you that they don't force us to pay.
