### ISSUE TITLE
Install app button text Chinese Simplified translation is wrong

### ISSUE THREAD

**Issue by greekstreet** [elementary/appcenter#828]
The current translation "清空" which is wrong. Original English text is "Free" which should be translated to Chinese as "安装"。

Or take Mac App Store as a reference, free app shows a button labeled as "Get". The translation to Chinese is "获取"。

![wrong text](https://user-images.githubusercontent.com/4527080/46183527-d8896000-c303-11e8-8fa4-f8d352c5d4c6.jpeg)

**Comment by danrabbit** [comment]
Thanks for noticing! All the translations for AppCenter are handled on Weblate [here](https://l10n.elementary.io/translate/appcenter/appcenter/zh_Hans/?type=all)

If you'd like to suggest translations, I'd recommend signing up there and joining our translators slack. More relevant information and links about localization is available [here](https://elementary.io/get-involved#translations)

Closing this as "Out of scope" for this repo since all translations are handled through Weblate
