### ISSUE TITLE
Cura 3.1.0 - AppCenter

### ISSUE THREAD

**Issue by abreumateus** [elementary/appcenter#870]
Hello,

I've just installed the latest Elementary OS 5.0 Juno and searched for Cura in the AppCenter and found that the version available is 3.1.0.
 
![image](https://user-images.githubusercontent.com/19293845/47289309-75bc7900-d5d0-11e8-8e3e-ea7da2d474e2.png)

Why isn't the latest version 3.5.1 like in the website for download - AppImage ?

![image](https://user-images.githubusercontent.com/19293845/47289325-879e1c00-d5d0-11e8-96d2-253ebb1952b8.png)

**Comment by peteruithoven** [comment]
When you run `sudo apt show cura` you can see some more information about the package. For example:
```
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
APT-Sources: http://nl.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
This means the mainstainers of the ubuntu universe repository haven't updated this package yet, some more information: https://help.ubuntu.com/community/Repositories/Ubuntu

It is quite common for packages to be older, which is why Cura for example also gives you the option to download a AppImage. 

Ultimaker also can't currently publish directly (under their own control) to the AppCenter since it's not build with a native (GTK) interface. In the future AppCenter might support packaging formats like Snap or Flatpak and things might change.
