### ISSUE TITLE
I can't see my app

### ISSUE THREAD

**Issue by panosx2** [elementary/appcenter#871]
I can't see my app at Elementary OS Loki's AppCenter
(https://appcenter.elementary.io/com.github.panosx2.brightness/)

**Comment by arshubham** [comment]
You need to create deb-packaging-loki orphan branch only with the debian folder in order to publish to loki. See https://github.com/elementary/houston/wiki/Before-You-Publish#packaging . By default it is only built for the latest version of the OS.

**Comment by panosx2** [comment]
thank you i didn't notice. could you please tell me how to do it?

**Comment by peteruithoven** [comment]
@panosx2 we hope our documentation is sufficient, could you clarify what's unclear?

**Comment by peteruithoven** [comment]
I'm closing this issue, since it's not an issue relating to AppCenter.

**Comment by arshubham** [comment]
@panosx2 First create a `orphan branch` (refer [this](https://stackoverflow.com/questions/1384325/in-git-is-there-a-simple-way-of-introducing-an-unrelated-branch-to-a-repository#4288660)) called `deb-packaging-loki` and add debin folder in there. Most of the times it will be same as juno (package name, versions may vary).
For packaging for juno create another orphan branch called `deb-packaging-juno`.

If you create a brach called `deb-packaging` it will always refer to the `lastest` version of elementary which is juno for now. When the _next version_ is released in order to release app for juno you need to created a `deb-packaging-juno` and the `deb-packaging` will refer to that version.

If you create a `debian folder in the master branch` it is **same** as creating a `deb-packaging` branch.

**Comment by panosx2** [comment]
i already have a debian folder in the master branch

**Comment by arshubham** [comment]
@panosx2 The debian folder in the master branch will always refer to the latest version of elementary. You need to create `deb-packaging-loki` for loki and `deb-packaging` for juno and remove debian folder from master.
