### ISSUE TITLE
Cannot use Japanese credit card to pay for some apps in appcenter

### ISSUE THREAD

**Issue by IKUWILL** [elementary/appcenter#879]
Was able to purchase torrential, but unable to purchase Nimbus or other apps with a valid card. 
Card is declined. Same issue on the download page. Patreon using paypal is successful. If a feature allowed for paypal to be used for payment in the appcenter, then it will be possible to purchase apps.

**Comment by eljefuri** [comment]
I am referencing #291 so that it can -- perhaps? -- become a general discussion point for this. Cards are far more rare globally than may generally be appreciated by Western people. We definitely need (many) alternative payment methods for this to be a truly global and inclusive project.

**Comment by cassidyjames** [comment]
@IKUWILL my guess is this is currency-related, since Torrential's developer is in the UK and Nimbus is in the US? It's an unfortunate side-effect of how the current payment system is set up, but there is work towards making it so that currency won't change per-developer. Once that is complete, we can tackle #280.

**Comment by cassidyjames** [comment]
@btkostner should this actually be filed against Houston?

**Comment by lennarthlion** [comment]
I am German and Germans usually don't use credit cards - at all. (some business people and travellers do i guess) 

We do have Giro-Cards instead.

When i tried to find a way to use stripe/the appcenter payment, i discovered that stripe once made an attempt apparently to involve Germany as a country by using "Giro-Pay". 
So i have the great need to tell you that my bank and certainly most other banks in Germany don't use Giro-Pay any more since at least 5 years or so. The last time I used it has been in 2010. I think it's pretty much dead. I didn't found any other sign that stripe would have found any solution for the "German problem" that is up to date.

I posted my problem in full here, concerning that "Agenda" has a minimum price.
https://elementaryos.stackexchange.com/questions/18666/cant-update-agenda-anymore-because-of-minimum-price-where-i-live-credit-card?noredirect=1#comment20426_18666

Germans are very privacy concerned by nature. It would not only be sad if elementary OS would kind of exclude our culture but also a bit ironic. 

Credit Cards cost money, hidden or obviously, and i prefer to invest that money in open source projects instead.

**Comment by cassidyjames** [comment]
@lennarthlion I'm not intimately familiar with EC cards in Germany, but they sound just like "debit cards" here in the states—it's similar to a credit card but withdraws directly from your bank account and is denied if there are not sufficient funds in the account. Do you know if it's possible to use an EC card online at all, and if so, does it work with AppCenter or Stripe? It sounds at first like it should, as debit cards work exactly like credit cards from the payment processor integration side.

If not, then unfortunately we are reliant on Stripe implementing some solution; we do 100% of our processing through them as they take care of massive amounts of technical, compliance, tax, and business obligations that we just would not be able to take on ourselves in order to implement other payment systems.

**Comment by matzipan** [comment]
Debit cards are fine with Stripe. It's also unclear for me whether Lennarth is saying he tried at all to pay with Girocard and couldn't.

**Comment by lennarthlion** [comment]
Oh i am very sorry for the confusion. I didn't know that German "EC Cards" have been renamed to Giro Cards in 2007. 
Obviously because that name lead to confusion before. Really sorry. Didn't know it and called them still wrong out of habit. 

So Giro Card it is. 

Giro uses the Iban and BIC Codes. https://www.iban.com/glossary
Such thing as the CVC simply don't exist.

I have nothing to fill in the appCenter.

Giro Cards are no Debit Cards at all. Sorry for the confusion again.

**Comment by lennarthlion** [comment]
Also i don't think Iban or Bic would be any use for a quick anywhere payment like you do it with a credit card. 

I really don't think you should involve the Giro Card system into the appcenter. Giro Pay have been a thing, apparently the last thing of online payment via Giro, stripe recognised. But Giro Pay is quite dead. I don't have it anymore. Used it the last time 2010. It doesn't exist on my card since at least 6 years or so. Didn't liked it also. 

Hoping to involve the Giro Card system is in my eyes not worth the effort. 
Giro Cards are not really made for online payment. 

Having a second payment option like paypal would solve the problem in Germany better.

**Comment by lennarthlion** [comment]
I know Germany and money is really weird. 

The supermarkets are full with gift cards for any online company you might imagine. Other people like me connect their paypal with everything online, like the play store or itunes store. (used gift cards for them before as well ...) 

Credit Cards are really unpopular. 

Behind that all stands the German mindset that you don't use money you don't have. The reason behind that is more culture related than anything. 

Of course business people and travellers and wealthy people who simply like having a Visa have it. But the usual German simply has a Giro Account and is fine.

**Comment by davidmhewitt** [comment]
I'm going to close this issue as we haven't had many recent reports about payment issues and it seemed to turn into a discussion about providing other payment methods, of which there are separate, more specific issues open for.
