### ISSUE TITLE
Unable to pay after filling out credit card details

### ISSUE THREAD

**Issue by wout** [elementary/appcenter#880]
I tried to pay for Ideogram but the pay button never came alive:

![image](https://user-images.githubusercontent.com/107324/47618810-aec88200-dad7-11e8-90fa-5123ff2d1aa2.png)

Checked all my details, twice, so no idea what else I can do.

FWIW, I started the payment process from this button:

![image](https://user-images.githubusercontent.com/107324/47618897-b50b2e00-dad8-11e8-8077-2a75dc22cabc.png)

But uninstalling and reinstalling while choosing an amount to pay results in the same problem. Then I'm not even able to download the app. 🙄

**Comment by Philip-Scott** [comment]
So what's going on is that the pay button is only enabled when all the details are considered "valid". 

The only think i could think of is that maybe your email is being considered invalid, or maybe we're doing something wrong with the CC validation... 

the things i could think of from the top of my head (without asking for your CC details xD)

- How many numbers are there in your credit card?
- Is your CVC maybe using letters instead of numbers?
- What email are you using?

**Comment by wout** [comment]
Exactly, triple checked all details now, everything is correct. I tried another card, same issue. I even used my company's Stripe email address and credit card, the button stays disabled. Whatever details I enter, the outcome is the same.

To come to your questions:
- All my cards have 16 digits
- They all have 3-digit CVC code
- I used three different email addresses, none of them make a difference

**Comment by wout** [comment]
I created a pull request, fixing the issue.
