### ISSUE TITLE
Idea: show approximate time spent on development of the app

### ISSUE THREAD

**Issue by dumblob** [elementary/appcenter#923]
Because of historical reasons, users of open source software are not much used to materially reward the software providers.

I think that an interesting push in the right way might be adding an information about the approximated effort in mandays to each app in the store (using any of [Software cost estimation models](https://en.wikipedia.org/wiki/Cost_estimation_in_software_engineering ) like *COCOMO II* etc. taking into consideration source code and its complexity and programming language and very much also other stuff like icons, artwork, multimedia, examples, etc. - of course including the stuff from external sources even if the money will go just to the author and you *elementary OS* guys, because first then it'll be theoretically possible to even pay something to the providers of the third party resources if any).

This way it would not just "push more" at the first installation, but also easily tell the user how much effort (and it's usually quite a lot) it was to put out a new version of the software.

The overall effort in software world is nowadays as well as historically by far the most underestimated thing and people (not just ordinary, but also experienced specialists) still don't fully grasp the difficulty and complexity of software development. At least the manday approximation (be it even 100% different from the reality) will be a big surprise for most of the people in the world (this is unfortunately no joke).

Either way, keep doing the good work and sticking to your principles (HIG + automated app ecosystem to name a few).

**Comment by danirabbit** [comment]
There's really no accurate way to calculate this tbh. I think it's a well intentioned idea, but I don't think it's really possible to do. Something we do have no is that we show a number of release notes and developers can include links to resolved issues in those release notes so we can show long term active development and community engagement.

Gonna close this as "Not planned" since it's not really possible to get any kind of accurate guess of the amount of effort that went into developing an app
